spring:
  application:
    name: lbgateway

  cloud:
    gateway:
     routes:
       - id: helloservice-route
         uri: lb://HELLOSERVICE
         predicates:
            - Path=/rest/service/**
server:
  port: 8075
  
management:
  endpoint:
    gateway:
      enabled: true  
  endpoints:
    web:
      exposure:
        include: "*"
  